<a href="https://colab.research.google.com/github/pesado-dev/DATA_SCIENCE/blob/main/desafioNBA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
df = pd.read_csv('/content/players_stats.csv')

In [12]:
print(df.describe())

       Games Played          MIN          PTS         FGM          FGA  \
count    490.000000   490.000000   490.000000  490.000000   490.000000
mean      53.014286  1214.714286   502.108163  188.338776   419.526531
std       24.175437   820.570132   422.084232  156.265752   337.367125
min        1.000000     3.000000     0.000000    0.000000     0.000000
25%       33.000000   492.250000   145.250000   55.500000   139.000000
50%       61.000000  1193.000000   423.000000  156.000000   357.500000
75%       74.000000  1905.750000   774.000000  286.000000   642.750000
max       83.000000  2981.000000  2217.000000  659.000000  1471.000000

              FG%         3PM        3PA         3P%         FTM  ...  \
count  490.000000  490.000000  490.00000  490.000000  490.000000  ...
mean    43.099184   39.387755  112.52449   25.519184   86.042857  ...
std      9.625231   47.880909  127.38575   15.796603   91.315316  ...
min      0.000000    0.000000    0.00000    0.000000    0.000000  ...
25%     39.600000    1.000000    6.00000   15.500000   18.500000  ...
50%     42.900000   18.000000   58.00000   31.300000   58.000000  ...
75%     47.575000   66.000000  192.00000   36.400000  126.750000  ...
max    100.000000  286.000000  646.00000  100.000000  715.000000  ...

              BLK         TOV          PF          EFF     AST/TOV  \
count  490.000000  490.000000  490.000000   490.000000  490.000000
mean    24.075510   68.826531  101.483673   564.330612    1.465837
std     31.662852   58.480701   65.326807   464.428031    0.825037
min      0.000000    0.000000    0.000000    -3.000000    0.000000
25%      5.000000   23.000000   45.500000   165.000000    0.920000
50%     14.000000   56.500000  103.000000   490.500000    1.345000
75%     29.750000  100.000000  148.750000   837.000000    1.920000
max    200.000000  321.000000  285.000000  2202.000000    6.500000

          STL/TOV         Age      Height      Weight         BMI
count  490.000000  422.000000  422.000000  422.000000  422.000000
mean     0.626000   27.507109  197.440758   99.469194   25.427747
std      0.367443    4.220603    8.740250   12.364228    1.715794
min      0.000000   20.000000  172.500000   72.450000   20.411523
25%      0.392500   24.000000  190.000000   90.000000   24.286136
50%      0.530000   27.000000  197.500000   99.000000   25.420833
75%      0.820000   30.000000  205.000000  108.000000   26.437500
max      3.000000   39.000000  222.500000  162.000000   32.723141

[8 rows x 27 columns]

In [3]:
df

,Name,Games Played,MIN,PTS,FGM,FGA,FG%,3PM,3PA,3P%,...,Age,Birth_Place,Birthdate,Collage,Experience,Height,Pos,Team,Weight,BMI
0,AJ Price,26,324,133,51,137,37.2,15,57,26.3,...,29.0,us,"October 7, 1986",University of Connecticut,5,185.0,PG,PHO,81.45,23.798393
1,Aaron Brooks,82,1885,954,344,817,42.1,121,313,38.7,...,30.0,us,"January 14, 1985",University of Oregon,6,180.0,PG,CHI,72.45,22.361111
2,Aaron Gordon,47,797,243,93,208,44.7,13,48,27.1,...,20.0,us,"September 16, 1995",University of Arizona,R,202.5,PF,ORL,99.00,24.142661
3,Adreian Payne,32,740,213,91,220,41.4,1,9,11.1,...,24.0,us,"February 19, 1991",Michigan State University,R,205.0,PF,ATL,106.65,25.377751
4,Al Horford,76,2318,1156,519,965,53.8,11,36,30.6,...,29.0,do,"June 3, 1986",University of Florida,7,205.0,C,ATL,110.25,26.234384
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,Xavier Henry,9,86,20,3,13,23.1,0,0,0.0,...,24.0,be,"March 15, 1991",University of Kansas,4,195.0,SF,LAL,99.00,26.035503
486,Zach LaVine,77,1902,778,286,677,42.2,57,167,34.1,...,20.0,us,"March 10, 1995","University of California, Los Angeles",R,192.5,PG,MIN,85.05,22.951594
487,Zach Randolph,71,2304,1143,454,932,48.7,7,20,35.0,...,34.0,us,"July 16, 1981",Michigan State University,13,202.5,PF,MEM,117.00,28.532236
488,Zaza Pachulia,73,1730,606,240,529,45.4,0,3,0.0,...,31.0,ge,"February 10, 1984",NaN,11,207.5,C,MIL,121.50,28.218900
489,Zoran Dragic,16,75,28,11,30,36.7,3,14,21.4,...,26.0,si,"June 22, 1989",NaN,R,192.5,SG,PHO,90.00,24.287401

In [5]:
# Filtrar os dados para incluir apenas os jogadores mencionados
players = ["Anthony Davis", "James Harden", "Victor Oladipo", "Damian Lillard"]
filtered_data = df[df['Name'].isin(players)]

# Calcular a taxa de aproveitamento de lances livres (FT%) para cada jogador
filtered_data['FT%'] = filtered_data['PTS'] / filtered_data['FTM']

# Identificar o jogador com a maior taxa de aproveitamento de lances livres
best_player = filtered_data.loc[filtered_data['FT%'].idxmax(), 'Name']

print("O jogador com a maior taxa de aproveitamento de lances livres é:", best_player)

O jogador com a maior taxa de aproveitamento de lances livres é: Damian Lillard

<ipython-input-5-26c962365f3b>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['FT%'] = filtered_data['PTS'] / filtered_data['FTM']

In [14]:
# Contar quantos jogadores ficaram apenas no banco de reserva sem participar de nenhum jogo
bench_players = df[df['Games Played'] == 0]
num_bench_players = len(bench_players)

print("Número de jogadores que ficaram apenas no banco de reserva sem participar de nenhum jogo:", num_bench_players)

Número de jogadores que ficaram apenas no banco de reserva sem participar de nenhum jogo: 0

In [17]:
# Contar quantos jogadores ficaram apenas no banco de reserva sem participar de nenhum jogo
bench_players = df[df['MIN'] == 0]
num_bench_players = len(bench_players)

print("Número de jogadores que ficaram apenas no banco de reserva sem participar de nenhum jogo:", num_bench_players)

Número de jogadores que ficaram apenas no banco de reserva sem participar de nenhum jogo: 0

In [22]:
# Calcular a métrica defensiva para cada jogador
df['Defensive Metric'] = (df['REB'] + df['BLK']) / df['MIN']

# Remover outliers com média de minutagem menor que 20
filtered_data = df[df['MIN'] >= 20]

# Filtrar os jogadores mencionados
players = ["Paul George", "Jeff Withey", "James Harden", "Omer Asik"]
filtered_players = filtered_data[filtered_data['Name'].isin(players)]

# Identificar o jogador com a maior métrica defensiva
best_defender = filtered_players.loc[filtered_players['Defensive Metric'].idxmax(), 'Name']

print("O jogador escolhido como o melhor defensor é:", best_defender)

O jogador escolhido como o melhor defensor é: Omer Asik

In [25]:
# Converter a coluna de datas para o formato datetime, se necessário
df['Birthdate'] = pd.to_datetime(df['Birthdate'])

# Filtrar os dados para incluir apenas jogos do dia 02 de Abril de 2014
games_2_april_2014 = df[df['Birthdate'] == '2014-04-02']

# Calcular o total de pontos feitos por todos os jogadores
total_points = games_2_april_2014['PTS'].sum()

print("O total de pontos feitos por todos os jogadores no dia 02 de Abril de 2014 é:", total_points)

O total de pontos feitos por todos os jogadores no dia 02 de Abril de 2014 é: 0